### ISSUE TITLE
LogicException when trying to upload 1200x836 JPG Image

### ISSUE THREAD

**Issue by Cuacha07** [gmlo89/simple-cms#1]
The following error shows up when i was changing the avatar image of my user on Edit User screen.

<b>LogicException in MimeTypeGuesser.php line 127:
Unable to guess the mime type as no guessers are available (Did you enable the php_fileinfo extension?)</b>

It seems to be a classical error of maximun file sizes and file types.

**Comment by gmlo89** [comment]
Hmm... Did you enable the php_fileinfo extension?

**Comment by Cuacha07** [comment]
i didn't! now it works XD haha
